import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          // appTitle
          'appTitle': '麻花宠物',
          // welcome
          'skip': '跳过',
          // tab配置
          'home': '首页',
          'found': '发现',
          'topic': '话题',
          'profile': '我的',
          // login_page
          'login': '登录',
          'mobile_phone_no': '手机号',
          'mobile_hintText': '请输入手机号',
          'password_phone_no': '密码',
          'password_hintText': '请输入密码',
          'rememberPassword': '记住密码',
          'account': '用户名',
          'password': '密码',
          // profile_page
          'not_logged': '未登录',
          'praise': '获赞',
          'fans': '粉丝',
          'attention': '关注',
          'my_pet': '我的宠物',
          'all': '全部',
          'set_the_theme': '设置主题',
          'select_theme': '选择主题',
          'default': '默认',
          'theme': '主题',
          'set_the_language': '设置语言',
          // setting_page
          'set': '设置',
          'log_out': '退出登录',
          'logging_out_successfully': '退出登录成功',
          // home_page
          'dynamic_details': '动态详情',
          'choose_a_pet': '选择宠物',
          'daily_clock': '日常打卡',
          'health_manage': '健康管理',
          'weight_record': '体重记录',
          'rookie_help': '新手帮助',
          'feeding_guide': '喂养指导',
          'pet_list': '宠物列表',
          'switch_success': '切换成功',
          'please_enter_a_nickname': '请输入昵称',
          'please_select_gender': '请选择性别',
          'please_enter_pet_breed': '请输入宠物品种',
          'please_select_your_date_of_birth': '请选择出生日期',
          'please_select_the_adoption_date': '请选择领养日期',
          'please_select_sterilization_status': '请选择绝育状态',
          'please_enter_your_pets_weight': '请输入宠物体重',
          'neutered': '已绝育',
          'unneutered': '未绝育',
          'modify_successfully': '修改成功',
          'edit_pet': '编辑宠物',
          'mandatory': '必填',
          'nickname': '昵称',
          'sex': '性别',
          'varieties_of_pet': '宠物品种',
          'date_of_birth': '出生日期',
          'adopt_of_birth': '领养日期',
          'sterilization_state': '绝育状态',
          'pet_weight': '宠物体重',
          'save': '保存',
          'recommend': '推荐',
          'dynamic': '动态',
           // found_page
          'focus': '关注',
          'you_probably_know_them': '你可能认识他们',
          'change': '换一换',
          'check_out_more_comments': '查看更多评论',
          'hot_topic': '热门话题',
          'more': '更多',
          'hot_discussion': '热门讨论',
          'hot': '热门',
          'all_question': '全部问题',
          // common
          'confirm': '确定',
          'cancel': '取消',
          'reply': '回复',
          'delete': '删除',
          'send': '发送',
          'temporarily_no_data': '暂无数据',
          'comment_on_cutie': '快来评论小可爱吧',
          'comment_messages_cannot_be_empty': '评论信息不能为空',
          'unfollowing_succeeded': '取消关注成功',
          'focus_on_success': '关注成功',
          'unliked_succeeded': '取消点赞成功',
          'thumb_up_success': '点赞成功',
          'unfavorites_successful': '取消收藏成功',
          'collection_of_success': '收藏成功',
        },
        'en_US': {
          // appTitle
          'appTitle': 'Twist the pet',
          // welcome
          'skip': 'skip',
          // tab配置
          'home': 'home',
          'found': 'found',
          'topic': 'topic',
          'profile': 'profile',
          // login_page
          'login': 'login',
          'mobile_phone_no': 'phone',
          'mobile_hintText': 'Please enter your mobile phone number',
          'password_phone_no': 'password',
          'password_hintText': 'Please enter your password',
          'rememberPassword': 'remember password',
          'account': 'account',
          'password': 'password',
          // profile_page
          'not_logged': 'not logged',
          'praise': 'praise',
          'fans': 'fans',
          'attention': 'attention',
          'my_pet': 'my pet',
          'all': 'all',
          'set_the_theme': 'set the theme',
          'select_theme': 'select theme',
          'default': 'default',
          'theme': 'theme',
          'set_the_language': 'set the language',
          // setting_page
          'set': 'set',
          'log_out': 'log out',
          'logging_out_successfully': 'logging out successfully',
          // home_page
          'dynamic_details': 'dynamic details',
          'choose_a_pet': 'choose a pet',
          'daily_clock': 'daily clock',
          'health_manage': 'health manage',
          'weight_record': 'weight record',
          'rookie_help': 'rookie help',
          'feeding_guide': 'feeding guide',
          'pet_list': 'pet list',
          'switch_success': 'switch success',
          'please_enter_a_nickname': 'please enter a nickname',
          'please_select_gender': 'please select gender',
          'please_enter_pet_breed': 'please enter pet breed',
          'please_select_your_date_of_birth': 'please select your date of birth',
          'please_select_the_adoption_date': 'please select the adoption date',
          'please_select_sterilization_status': 'please select sterilization status',
          'please_enter_your_pets_weight': 'please enter your pets weight',
          'neutered': 'neutered',
          'unneutered': 'unneutered',
          'modify_successfully': 'modify successfully',
          'edit_pet': 'edit pet',
          'mandatory': 'mandatory',
          'nickname': 'nickname',
          'sex': 'sex',
          'varieties_of_pet': 'varieties of pet',
          'date_of_birth': 'date of birth',
          'adopt_of_birth': 'adopt of birth',
          'sterilization_state': 'sterilization state',
          'pet_weight': 'pet weight',
          'save': 'save',
          'recommend': 'recommend',
          'dynamic': 'dynamic',
          // found_page
          'focus': 'focus',
          'you_probably_know_them': 'you probably know them',
          'change': 'change',
          'check_out_more_comments': 'check out more comments',
          'hot_topic': 'hot topic',
          'more': 'more',
          'hot_discussion': 'hot discussion',
          'hot': 'hot',
          'all_question': 'all question',
          // common
          'confirm': 'confirm',
          'cancel': 'cancel',
          'reply': 'reply',
          'delete': 'delete',
          'send': 'send',
          'temporarily_no_data': '暂无数据',
          'comment_on_cutie': 'comment on cutie',
          'comment_messages_cannot_be_empty': 'comment messages cannot be empty',
          'unfollowing_succeeded': 'unfollowing succeeded',
          'focus_on_success': 'focus on success',
          'unliked_succeeded': 'unliked succeeded',
          'thumb_up_success': 'thumb up success',
          'unfavorites_successful': 'unfavorites successful',
          'collection_of_success': 'collection of success',
        }
      };

}